In [1]:
import torch
import torch.nn as nn
print(torch.__version__)

2.6.0+cu124


In [2]:
import torch
import torch.nn as nn

class Model(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.network = nn.Sequential(
        nn.Linear(num_features, 1),
        nn.Sigmoid()
    )

  def forward(self, features):

    out = self.network(features)

    return out

In [3]:
features = torch.rand(10,5)

In [4]:
model = Model(features.shape[1])

In [5]:
model(features)

tensor([[0.3645],
        [0.3490],
        [0.3903],
        [0.4144],
        [0.4317],
        [0.4809],
        [0.3554],
        [0.4058],
        [0.3717],
        [0.4505]], grad_fn=<SigmoidBackward0>)

In [6]:
import torch
import torch.nn as nn
print(torch.__version__)

2.6.0+cu124


In [7]:
class mynn(nn.Module):
  def __init__(self, num_features):
    super().__init__()
    self.network = nn.Sequential(
        nn.Linear(num_features, 5),
        nn.ReLU(),
        nn.Linear(5,3),
        nn.Sigmoid(),
        nn.Linear(3,1),
        nn.Sigmoid()
    )

  def forward(self, features):
    out = self.network(features)
    return out

In [8]:
features  = torch.rand(10,10)

In [9]:
model = mynn(features.shape[1])
model

mynn(
  (network): Sequential(
    (0): Linear(in_features=10, out_features=5, bias=True)
    (1): ReLU()
    (2): Linear(in_features=5, out_features=3, bias=True)
    (3): Sigmoid()
    (4): Linear(in_features=3, out_features=1, bias=True)
    (5): Sigmoid()
  )
)

In [10]:
model(features)

tensor([[0.4477],
        [0.4493],
        [0.4522],
        [0.4502],
        [0.4468],
        [0.4505],
        [0.4470],
        [0.4536],
        [0.4533],
        [0.4497]], grad_fn=<SigmoidBackward0>)

In [11]:
!pip install torchinfo

In [12]:
from torchinfo import summary
summary(model, input_size = (10, 10))

Layer (type:depth-idx)                   Output Shape              Param #
mynn                                     [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 5]                   55
│    └─ReLU: 2-2                         [10, 5]                   --
│    └─Linear: 2-3                       [10, 3]                   18
│    └─Sigmoid: 2-4                      [10, 3]                   --
│    └─Linear: 2-5                       [10, 1]                   4
│    └─Sigmoid: 2-6                      [10, 1]                   --
Total params: 77
Trainable params: 77
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

Third Practice

In [13]:
import torch
import torch.nn as nn
print(torch.__version__)

2.6.0+cu124


In [25]:
class mynn(nn.Module):
  def __init__(self, num_features):
    super().__init__()

    self.network = nn.Sequential(
        nn.Linear(num_features, 5),
        nn.ReLU(),
        nn.Linear(5,1),
        nn.Sigmoid()
    )

  def forward(self, features):
    out  = self.network(features)
    return out

In [26]:
features  = torch.rand(10,10)

In [27]:
model = mynn(features.shape[1])
model

mynn(
  (network): Sequential(
    (0): Linear(in_features=10, out_features=5, bias=True)
    (1): ReLU()
    (2): Linear(in_features=5, out_features=1, bias=True)
    (3): Sigmoid()
  )
)

In [28]:
model(features)

tensor([[0.5177],
        [0.4907],
        [0.4759],
        [0.4896],
        [0.4989],
        [0.4950],
        [0.5324],
        [0.4755],
        [0.4883],
        [0.5174]], grad_fn=<SigmoidBackward0>)

In [31]:
model.network

Sequential(
  (0): Linear(in_features=10, out_features=5, bias=True)
  (1): ReLU()
  (2): Linear(in_features=5, out_features=1, bias=True)
  (3): Sigmoid()
)