In [90]:
# import torch and check version
import torch
print(torch.__version__)

2.6.0+cu124


In [91]:
#use cuda or cpu
if torch.cuda.is_available():
  print("cuda is available")
  print("cuda device we are using is ", torch.cuda.current_device())
  print("current gpu we are using is", torch.cuda.get_device_name(0))
else:
  print("we are using cpu")

cuda is available
cuda device we are using is  0
current gpu we are using is Tesla T4


creating a simple tensors

In [92]:
#initalize empty tensor
a= torch.empty(2,3)
a

tensor([[2.1715e-18, 2.3081e-12, 1.8590e+34],
        [7.7767e+31, 1.7181e+19, 1.8990e+28]])

In [93]:
b= torch.ones(2,6)
b

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [94]:
type(a)

torch.Tensor

In [95]:
c = torch.zeros(3,3)
c

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [96]:
d = torch.rand(3,3)
d

tensor([[0.7109, 0.0148, 0.7262],
        [0.4660, 0.0610, 0.7108],
        [0.5127, 0.8211, 0.1323]])

In [97]:
e = torch.rand(3,3)
e

tensor([[0.2127, 0.9785, 0.3362],
        [0.7165, 0.1591, 0.2860],
        [0.1827, 0.7421, 0.5736]])

In [98]:
torch.manual_seed(100)
f = torch.rand(3,3)
f

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539],
        [0.2627, 0.0428, 0.2080]])

In [99]:
torch.manual_seed(100)
f = torch.rand(3,3)
f

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539],
        [0.2627, 0.0428, 0.2080]])

In [100]:
a = torch.arange(0,10)
a

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [101]:
b = torch.arange(0,20,2)
b

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [102]:
c = torch.linspace(0, 20, 7)
c

tensor([ 0.0000,  3.3333,  6.6667, 10.0000, 13.3333, 16.6667, 20.0000])

In [103]:
d = torch.eye(5)
d

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [104]:
e = torch.full((10,10),2)
e

tensor([[2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2]])

tensor shapes

In [105]:
a = torch.rand(3,3)
a

tensor([[0.1180, 0.1217, 0.7356],
        [0.7118, 0.7876, 0.4183],
        [0.9014, 0.9969, 0.7565]])

In [106]:
a.shape

torch.Size([3, 3])

In [107]:
b = torch.empty_like(a)
b

tensor([[6.5450e-19, 0.0000e+00, 6.9346e-19],
        [0.0000e+00, 1.1210e-43, 0.0000e+00],
        [8.9683e-44, 0.0000e+00, 8.1095e-16]])

In [108]:
c = torch.zeros_like(a)
c

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [109]:
d = torch.ones_like(a)
d

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [110]:
e = torch.rand_like((a), dtype=torch.float32)
e

tensor([[0.2239, 0.3023, 0.1784],
        [0.8238, 0.5557, 0.9770],
        [0.4440, 0.9478, 0.7445]])

Tensors Data Types

In [111]:
a = torch.rand(3,3)
a

tensor([[0.4892, 0.2426, 0.7003],
        [0.5277, 0.2472, 0.7909],
        [0.4235, 0.0169, 0.2209]])

In [112]:
a.dtype

torch.float32

In [113]:
b = torch.tensor(([1,2,3],[4,5,6]), dtype=torch.float64)
b

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)

In [114]:
c = torch.tensor(a, dtype=torch.int64)
c

<ipython-input-114-4069ca93534a>:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  c = torch.tensor(a, dtype=torch.int64)


tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [115]:
a.to(dtype=torch.int64)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

Mathematical Operation in Tensors

In [116]:
a = torch.rand(3,3)
a

tensor([[0.9535, 0.7064, 0.1629],
        [0.8902, 0.5163, 0.0359],
        [0.6476, 0.3430, 0.3182]])

In [117]:
a + 2

tensor([[2.9535, 2.7064, 2.1629],
        [2.8902, 2.5163, 2.0359],
        [2.6476, 2.3430, 2.3182]])

In [118]:
a - 2

tensor([[-1.0465, -1.2936, -1.8371],
        [-1.1098, -1.4837, -1.9641],
        [-1.3524, -1.6570, -1.6818]])

In [119]:
a * 2

tensor([[1.9071, 1.4128, 0.3258],
        [1.7804, 1.0325, 0.0718],
        [1.2953, 0.6861, 0.6365]])

Element wise operation in tensors

In [120]:
a = torch.rand(3,3)
a

tensor([[0.5261, 0.0447, 0.5123],
        [0.9051, 0.5989, 0.4450],
        [0.7278, 0.4563, 0.3389]])

In [121]:
b = torch.rand(3,3)
b

tensor([[0.6211, 0.5530, 0.6896],
        [0.3687, 0.9053, 0.8356],
        [0.3039, 0.6726, 0.5740]])

In [122]:
a+b

tensor([[1.1472, 0.5977, 1.2020],
        [1.2738, 1.5041, 1.2806],
        [1.0317, 1.1289, 0.9128]])

In [123]:
a-b

tensor([[-0.0951, -0.5084, -0.1773],
        [ 0.5363, -0.3064, -0.3906],
        [ 0.4239, -0.2164, -0.2351]])

In [124]:
a*b

tensor([[0.3268, 0.0247, 0.3533],
        [0.3337, 0.5421, 0.3718],
        [0.2212, 0.3069, 0.1945]])

In [125]:
a/b

tensor([[0.8470, 0.0808, 0.7430],
        [2.4545, 0.6615, 0.5326],
        [2.3949, 0.6783, 0.5904]])

In [126]:
a = torch.tensor(([-1,2,3],[4,-5,6.5]))
print(a)
c = torch.abs(a)
print(c)

tensor([[-1.0000,  2.0000,  3.0000],
        [ 4.0000, -5.0000,  6.5000]])
tensor([[1.0000, 2.0000, 3.0000],
        [4.0000, 5.0000, 6.5000]])


In [127]:
d = torch.neg(a)
d

tensor([[ 1.0000, -2.0000, -3.0000],
        [-4.0000,  5.0000, -6.5000]])

In [128]:
e = torch.round(a)
e

tensor([[-1.,  2.,  3.],
        [ 4., -5.,  6.]])

In [129]:
f = torch.ceil(a)
f

tensor([[-1.,  2.,  3.],
        [ 4., -5.,  7.]])

In [130]:
g = torch.floor(a)
g

tensor([[-1.,  2.,  3.],
        [ 4., -5.,  6.]])

In [131]:
h = torch.clamp(a, 4,6)
h

tensor([[4., 4., 4.],
        [4., 4., 6.]])

Reduction Operation

In [132]:
a = torch.randint(size = (3,3), low = 0, high = 10)
a= a.to(dtype=torch.float64)

In [133]:
torch.sum(a)

tensor(40., dtype=torch.float64)

In [134]:
torch.sum((a), dim=0)

tensor([17.,  6., 17.], dtype=torch.float64)

In [135]:
torch.sum((a), dim = 1)

tensor([15., 14., 11.], dtype=torch.float64)

In [136]:
torch.mean(a)

tensor(4.4444, dtype=torch.float64)

In [137]:
torch.mean(a, dim=0)

tensor([5.6667, 2.0000, 5.6667], dtype=torch.float64)

In [138]:
torch.median(a)

tensor(4., dtype=torch.float64)

In [139]:
torch.median((a), dim=0)


torch.return_types.median(
values=tensor([5., 3., 6.], dtype=torch.float64),
indices=tensor([2, 0, 2]))

In [140]:
torch.max(a)

tensor(8., dtype=torch.float64)

In [141]:
torch.min(a)

tensor(0., dtype=torch.float64)

In [142]:
torch.std(a)

tensor(2.6034, dtype=torch.float64)

statiscs

In [143]:
a = torch.randint(low = 5, high = 50, size= (3,2))
b = torch.randint(low = 1, high = 10, size=(2,3))
print(a)
print(b)

tensor([[14,  5],
        [23, 24],
        [47, 17]])
tensor([[3, 6, 3],
        [9, 4, 6]])


In [144]:
c= torch.matmul(a,b)
c

tensor([[ 87, 104,  72],
        [285, 234, 213],
        [294, 350, 243]])

In [145]:
vector1 = torch.tensor([1,2,3])
vector2 = torch.tensor([4,5,6])
print(vector1)
print(vector2)

tensor([1, 2, 3])
tensor([4, 5, 6])


In [146]:
c = torch.dot(vector1, vector2)
c

tensor(32)

In [147]:
d = torch.transpose(a, 0, 1)
d

tensor([[14, 23, 47],
        [ 5, 24, 17]])

Camparison Operations

In [148]:
a = torch.randint(size = (3,3), low = 10, high = 50)
print(a)
b = torch.randint(size = (3,3), low = 0, high =40)
print(b)

tensor([[15, 30, 44],
        [42, 37, 21],
        [21, 15, 24]])
tensor([[24, 21,  1],
        [12, 34, 27],
        [22, 35, 36]])


In [149]:
a > b

tensor([[False,  True,  True],
        [ True,  True, False],
        [False, False, False]])

In [150]:
a< b

tensor([[ True, False, False],
        [False, False,  True],
        [ True,  True,  True]])

In [151]:
a>=b

tensor([[False,  True,  True],
        [ True,  True, False],
        [False, False, False]])

Inplace Operations

In [152]:
a.add_(b)

tensor([[39, 51, 45],
        [54, 71, 48],
        [43, 50, 60]])

copying a tensor

In [153]:
a = b

In [154]:
a

tensor([[24, 21,  1],
        [12, 34, 27],
        [22, 35, 36]])

In [155]:
b

tensor([[24, 21,  1],
        [12, 34, 27],
        [22, 35, 36]])

In [156]:
id(a)

133344011011472

In [157]:
id(b)

133344011011472

In [158]:
b= a.clone()

In [159]:
id(b)

133344011010896

In [160]:
id(a)

133344011011472

In [161]:
a[0][0]= 23

In [162]:
a

tensor([[23, 21,  1],
        [12, 34, 27],
        [22, 35, 36]])

In [163]:
b

tensor([[24, 21,  1],
        [12, 34, 27],
        [22, 35, 36]])

Reshape tensors

In [164]:
a = torch.rand(4,4)
b = torch.rand(5,5)
print(a)
print(b)

tensor([[0.5224, 0.4175, 0.0340, 0.9157],
        [0.3079, 0.6269, 0.8277, 0.6594],
        [0.0887, 0.4890, 0.5887, 0.7340],
        [0.8497, 0.9112, 0.4847, 0.9436]])
tensor([[0.3904, 0.2499, 0.3206, 0.9753, 0.7582],
        [0.6688, 0.2651, 0.2336, 0.5057, 0.5688],
        [0.0634, 0.8993, 0.2732, 0.3397, 0.1879],
        [0.5534, 0.2682, 0.9556, 0.9761, 0.5934],
        [0.3124, 0.9431, 0.8519, 0.9815, 0.1132]])


In [165]:
a.reshape(2,2,2,2)

tensor([[[[0.5224, 0.4175],
          [0.0340, 0.9157]],

         [[0.3079, 0.6269],
          [0.8277, 0.6594]]],


        [[[0.0887, 0.4890],
          [0.5887, 0.7340]],

         [[0.8497, 0.9112],
          [0.4847, 0.9436]]]])

In [166]:
a.flatten()

tensor([0.5224, 0.4175, 0.0340, 0.9157, 0.3079, 0.6269, 0.8277, 0.6594, 0.0887,
        0.4890, 0.5887, 0.7340, 0.8497, 0.9112, 0.4847, 0.9436])

In [167]:
import numpy as np

In [168]:
a = torch.rand(3,3)
a


tensor([[0.4783, 0.4436, 0.3847],
        [0.4521, 0.5569, 0.9952],
        [0.0015, 0.0813, 0.4907]])

In [169]:
a.shape

torch.Size([3, 3])

In [170]:
b= a.numpy()
b


array([[0.47829574, 0.4436491 , 0.38473564],
       [0.45208263, 0.5568533 , 0.99522525],
       [0.00148922, 0.0812639 , 0.49073827]], dtype=float32)

In [171]:
b.shape

(3, 3)

In [172]:
 c = torch.from_numpy(b)
 c

tensor([[0.4783, 0.4436, 0.3847],
        [0.4521, 0.5569, 0.9952],
        [0.0015, 0.0813, 0.4907]])

In [173]:
c.shape

torch.Size([3, 3])

GPU IMplemtation

In [174]:
import torch

In [175]:
if torch.cuda.is_available():
  print("wow, i am using gpu")

wow, i am using gpu


In [176]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
device

device(type='cuda')

In [177]:
import time
a = torch.rand(10000,10000)
b = torch.rand(10000, 10000)

start_cpu = time.time()
c = torch.matmul(a,b)
end_cpu = time.time()

differnece_cpu = end_cpu - start_cpu
print(differnece_cpu)

a = a.to(device)
b = b.to(device)
start_gpu = time.time()
c = torch.matmul(a,b)
end_gpu = time.time()

differnece_gpu = end_gpu - start_gpu
print(differnece_gpu)


15.532696008682251
0.0002880096435546875
