In [46]:
import torch
print(torch.__version__)

2.6.0+cu124


In [47]:
import sklearn
from sklearn.datasets import make_classification


In [48]:
x, y = make_classification(n_samples=10, n_features=2, n_informative=2, n_redundant=0, random_state=1)

In [49]:
x

array([[-1.52637437, -2.85961623],
       [-4.42287433,  0.70896364],
       [-1.55118469,  1.03584131],
       [-0.60483688, -2.00875146],
       [-3.42524143,  1.49509867],
       [ 1.44634283, -1.14651383],
       [-1.60290743, -1.52320683],
       [ 0.78712117,  0.55132541],
       [ 1.37496472, -0.22942496],
       [ 1.23169963,  1.72073855]])

In [50]:
y

array([0, 1, 1, 0, 1, 0, 0, 1, 0, 1])

In [51]:
X = torch.from_numpy(x)
Y = torch.from_numpy(y)

In [52]:
X

tensor([[-1.5264, -2.8596],
        [-4.4229,  0.7090],
        [-1.5512,  1.0358],
        [-0.6048, -2.0088],
        [-3.4252,  1.4951],
        [ 1.4463, -1.1465],
        [-1.6029, -1.5232],
        [ 0.7871,  0.5513],
        [ 1.3750, -0.2294],
        [ 1.2317,  1.7207]], dtype=torch.float64)

In [53]:
Y

tensor([0, 1, 1, 0, 1, 0, 0, 1, 0, 1])

In [54]:
from torch.utils.data import Dataset, DataLoader

In [55]:
class CustomDataset(Dataset):

  def __init__(self, features, labels):
    self.features = features
    self.labels = labels

  def __len__(self):
    return len(self.features)

  def __getitem__(self, index):
    return self.features[index], self.labels[index]

In [56]:
dataset = CustomDataset(X, Y)
dataset

In [57]:
len(dataset)

10

In [58]:
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)

In [59]:
for batch_features, batch_labels in dataloader:
  print(batch_features)
  print(batch_labels)

tensor([[-1.5512,  1.0358],
        [ 1.2317,  1.7207]], dtype=torch.float64)
tensor([1, 1])
tensor([[-3.4252,  1.4951],
        [-1.6029, -1.5232]], dtype=torch.float64)
tensor([1, 0])
tensor([[ 1.3750, -0.2294],
        [ 1.4463, -1.1465]], dtype=torch.float64)
tensor([0, 0])
tensor([[-0.6048, -2.0088],
        [ 0.7871,  0.5513]], dtype=torch.float64)
tensor([0, 1])
tensor([[-4.4229,  0.7090],
        [-1.5264, -2.8596]], dtype=torch.float64)
tensor([1, 0])


Practice Example

In [60]:
import pandas as pd
import numpy as np

In [61]:
data = pd.read_csv("BreastCancer.csv")
data

Id  Cl.thickness  Cell.size  Cell.shape  Marg.adhesion  \
0    1000025             5          1           1              1   
1    1002945             5          4           4              5   
2    1015425             3          1           1              1   
3    1016277             6          8           8              1   
4    1017023             4          1           1              3   
..       ...           ...        ...         ...            ...   
694   776715             3          1           1              1   
695   841769             2          1           1              1   
696   888820             5         10          10              3   
697   897471             4          8           6              4   
698   897471             4          8           8              5   

     Epith.c.size  Bare.nuclei  Bl.cromatin  Normal.nucleoli  Mitoses  Class  
0               2          1.0            3                1        1      0  
1               7         10.0            3                2        1      0  
2               2          2.0            3                1        1      0  
3               3          4.0            3                7        1      0  
4               2          1.0            3                1        1      0  
..            ...          ...          ...              ...      ...    ...  
694             3          2.0            1                1        1      0  
695             2          1.0            1                1        1      0  
696             7          3.0            8               10        2      1  
697             3          4.0           10                6        1      1  
698             4          5.0           10                4        1      1  

[699 rows x 11 columns]

In [62]:
data.columns

Index(['Id', 'Cl.thickness', 'Cell.size', 'Cell.shape', 'Marg.adhesion',
       'Epith.c.size', 'Bare.nuclei', 'Bl.cromatin', 'Normal.nucleoli',
       'Mitoses', 'Class'],
      dtype='object')

In [63]:
drop_id = data.drop(['Id'], axis=1)
drop_id

Cl.thickness  Cell.size  Cell.shape  Marg.adhesion  Epith.c.size  \
0               5          1           1              1             2   
1               5          4           4              5             7   
2               3          1           1              1             2   
3               6          8           8              1             3   
4               4          1           1              3             2   
..            ...        ...         ...            ...           ...   
694             3          1           1              1             3   
695             2          1           1              1             2   
696             5         10          10              3             7   
697             4          8           6              4             3   
698             4          8           8              5             4   

     Bare.nuclei  Bl.cromatin  Normal.nucleoli  Mitoses  Class  
0            1.0            3                1        1      0  
1           10.0            3                2        1      0  
2            2.0            3                1        1      0  
3            4.0            3                7        1      0  
4            1.0            3                1        1      0  
..           ...          ...              ...      ...    ...  
694          2.0            1                1        1      0  
695          1.0            1                1        1      0  
696          3.0            8               10        2      1  
697          4.0           10                6        1      1  
698          5.0           10                4        1      1  

[699 rows x 10 columns]

In [64]:
data_fillna = drop_id.fillna(0)
data_fillna

Cl.thickness  Cell.size  Cell.shape  Marg.adhesion  Epith.c.size  \
0               5          1           1              1             2   
1               5          4           4              5             7   
2               3          1           1              1             2   
3               6          8           8              1             3   
4               4          1           1              3             2   
..            ...        ...         ...            ...           ...   
694             3          1           1              1             3   
695             2          1           1              1             2   
696             5         10          10              3             7   
697             4          8           6              4             3   
698             4          8           8              5             4   

     Bare.nuclei  Bl.cromatin  Normal.nucleoli  Mitoses  Class  
0            1.0            3                1        1      0  
1           10.0            3                2        1      0  
2            2.0            3                1        1      0  
3            4.0            3                7        1      0  
4            1.0            3                1        1      0  
..           ...          ...              ...      ...    ...  
694          2.0            1                1        1      0  
695          1.0            1                1        1      0  
696          3.0            8               10        2      1  
697          4.0           10                6        1      1  
698          5.0           10                4        1      1  

[699 rows x 10 columns]

In [65]:
import sklearn

In [66]:
x_numpy = data.drop(['Class'], axis= 1)
x_numpy

Id  Cl.thickness  Cell.size  Cell.shape  Marg.adhesion  \
0    1000025             5          1           1              1   
1    1002945             5          4           4              5   
2    1015425             3          1           1              1   
3    1016277             6          8           8              1   
4    1017023             4          1           1              3   
..       ...           ...        ...         ...            ...   
694   776715             3          1           1              1   
695   841769             2          1           1              1   
696   888820             5         10          10              3   
697   897471             4          8           6              4   
698   897471             4          8           8              5   

     Epith.c.size  Bare.nuclei  Bl.cromatin  Normal.nucleoli  Mitoses  
0               2          1.0            3                1        1  
1               7         10.0            3                2        1  
2               2          2.0            3                1        1  
3               3          4.0            3                7        1  
4               2          1.0            3                1        1  
..            ...          ...          ...              ...      ...  
694             3          2.0            1                1        1  
695             2          1.0            1                1        1  
696             7          3.0            8               10        2  
697             3          4.0           10                6        1  
698             4          5.0           10                4        1  

[699 rows x 10 columns]

In [67]:
y_numpy = data_fillna['Class']
y_numpy

0      0
1      0
2      0
3      0
4      0
      ..
694    0
695    0
696    1
697    1
698    1
Name: Class, Length: 699, dtype: int64

In [68]:
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [69]:
X_train, X_test, Y_train, Y_test = train_test_split(x_numpy, y_numpy, test_size=0.2, random_state=42)

In [70]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [71]:
print(X_train.shape)
print(X_test.shape)
print(Y_train.shape)
print(Y_test.shape)

(559, 10)
(140, 10)
(559,)
(140,)


In [72]:
from torch.utils.data import Dataset, DataLoader

In [73]:
class CustomDataset(Dataset):

  def __init__(self, features, labels):
    self.features = torch.tensor(features, dtype = torch.float32)
    self.labels = torch.tensor(labels.to_numpy(), dtype = torch.long)

  def __len__(self):
    return len(self.features)

  def __getitem__(self, index):
    return self.features[index], self.labels[index]

In [74]:
train_dataset = CustomDataset(X_train, Y_train)
test_dataset = CustomDataset(X_test, Y_test)

In [75]:
train_dataset

In [76]:
test_dataset

In [77]:
train_dataloader = DataLoader(train_dataset, batch_size=2, shuffle=True)
test_dataloader = DataLoader(test_dataset, batch_size=2, shuffle=True)

In [78]:
import torch.nn as nn

In [79]:
class mynn(nn.Module):
  def __init__(self, num_features):
    super().__init__()
    self.network = nn.Sequential(
        nn.Linear(num_features, 5),
        nn.ReLU(),
        nn.Linear(5, 1),
        nn.Sigmoid()
    )

  def forward(self, features):
    out = self.network(features)
    return out

In [80]:
model = mynn(X_train.shape[1])

In [81]:
model

mynn(
  (network): Sequential(
    (0): Linear(in_features=10, out_features=5, bias=True)
    (1): ReLU()
    (2): Linear(in_features=5, out_features=1, bias=True)
    (3): Sigmoid()
  )
)

In [82]:
optimizer = torch.optim.SGD(model.parameters(), lr = 1e-4)

loss_funcyion = nn.BCELoss()

In [83]:
epochs = 25

In [85]:
for epoch in range(epochs):
  for batch_features, batch_labels in train_dataloader:
    # Ensure data types are correct and labels have the correct shape
    y_pred = model(batch_features.float())
    loss = loss_funcyion(y_pred, batch_labels)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

ValueError: Using a target size (torch.Size([2])) that is different to the input size (torch.Size([2, 1])) is deprecated. Please ensure they have the same size.

In [ ]:
# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fRp9RU51smTckIlMCO8yTlk1jMIhtH7U
"""

import torch
print(torch.__version__)

from sklearn.datasets import make_classification

# Generate synthetic data
x, y = make_classification(n_samples=10, n_features=2, n_informative=2, n_redundant=0, random_state=1)

# Convert to PyTorch tensors
X = torch.from_numpy(x.astype('float32'))
Y = torch.from_numpy(y.astype('float32'))

from torch.utils.data import Dataset, DataLoader

# Custom Dataset class
class CustomDataset(Dataset):
    def __init__(self, features, labels):
        self.features = features
        self.labels = labels

    def __len__(self):
        return len(self.features)

    def __getitem__(self, index):
        return self.features[index], self.labels[index]

# Create dataset and dataloader
dataset = CustomDataset(X, Y)
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)

# Print batches
for batch_features, batch_labels in dataloader:
    print(batch_features)
    print(batch_labels)

"""Practice Example"""

import pandas as pd
import numpy as np

# Load dataset
data = pd.read_csv("BreastCancer.csv")

# Drop 'Id' column
drop_id = data.drop(['Id'], axis=1)

# Fill missing values
data_fillna = drop_id.fillna(0)

# Split features and labels
x_numpy = data_fillna.drop(['Class'], axis=1).values.astype('float32')
y_numpy = data_fillna['Class'].values.astype('float32')

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Train-test split
X_train, X_test, Y_train, Y_test = train_test_split(x_numpy, y_numpy, test_size=0.2, random_state=42)

# Standardize features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train).astype('float32')
X_test = scaler.transform(X_test).astype('float32')

# Convert to PyTorch tensors
X_train = torch.from_numpy(X_train)
X_test = torch.from_numpy(X_test)
Y_train = torch.from_numpy(Y_train)
Y_test = torch.from_numpy(Y_test)

print(X_train.shape)
print(X_test.shape)
print(Y_train.shape)
print(Y_test.shape)

# Custom Dataset class for train and test data
train_dataset = CustomDataset(X_train, Y_train)
test_dataset = CustomDataset(X_test, Y_test)

# DataLoaders for train and test data
train_dataloader = DataLoader(train_dataset, batch_size=2, shuffle=True)
test_dataloader = DataLoader(test_dataset, batch_size=2, shuffle=True)

import torch.nn as nn

# Define the neural network
class mynn(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(num_features, 5),
            nn.ReLU(),
            nn.Linear(5, 1),
            nn.Sigmoid()
        )

    def forward(self, features):
        out = self.network(features)
        return out

# Initialize model, optimizer, and loss function
model = mynn(X_train.shape[1])
optimizer = torch.optim.SGD(model.parameters(), lr=0.000002)
loss_function = nn.BCELoss()

# Training loop
epochs = 25
for epoch in range(epochs):
    for batch_features, batch_labels in train_dataloader:
        # Ensure data types are correct and labels have the correct shape
        y_pred = model(batch_features.float())
        loss = loss_function(y_pred, batch_labels.float().unsqueeze(1))

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
    print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')